git checkout -b apple-llvmgcc42 010345095b7491a93b1b48ad5cea69797dd131a0; curl -L http://opensource.apple.com/tarballs/llvmgcc42/llvmgcc42-2336.11.tar.gz | tar x --strip-components 1; git add --all

diff --git a/build_gcc b/build_gcc
--- a/build_gcc
+++ b/build_gcc
@@ -69,9 +69,9 @@ DEST_DIR="$5"
 SYM_DIR="$6"
 
 # LLVM LOCAL begin
-# The seventh parameter is true/false indicating whether LLVM should be enabled
-# or not.
-ENABLE_LLVM="$7"
+# The seventh parameter is a yes/no that indicates whether libLTO.dylib
+# should be installed from LLVMCORE_PATH.
+INSTALL_LIBLTO="$7"
 
 # The eighth parameter is a yes/no that indicates whether assertions should be
 # enabled in the LLVM libs/tools.
@@ -85,6 +85,8 @@ LLVM_SUBMIT_VERSION="${10}"
 
 # The eleventh parameter is the subversion number of the submission, e.g. 03.
 LLVM_SUBMIT_SUBVERSION="${11}"
+
+ENABLE_LLVM=true
 
 # LLVM LOCAL end
 
@@ -116,6 +118,10 @@ fi
 NON_ARM_CONFIGFLAGS="--with-gxx-include-dir=/usr/include/c++/$LIBSTDCXX_VERSION"
 # LLVM LOCAL end
 
+# Build against the MacOSX10.5 SDK for PowerPC.
+PPC_SYSROOT=/Developer/SDKs/MacOSX10.5.sdk
+PPC_CONFIGFLAGS="$NON_ARM_CONFIGFLAGS --with-build-sysroot=\"$PPC_SYSROOT\""
+
 DARWIN_VERS=`uname -r | sed 's/\..*//'`
 echo DARWIN_VERS = $DARWIN_VERS
 
@@ -123,36 +129,24 @@ echo DARWIN_VERS = $DARWIN_VERS
 ARM_LIBSTDCXX_VERSION=4.2.1
 ARM_CONFIGFLAGS="--with-gxx-include-dir=/usr/include/c++/$ARM_LIBSTDCXX_VERSION"
 
-if [ -n "$ARM_SDK" ]; then
+# When building for a non-embedded train, ARM defaults to MacOSX, just like
+# x86 and ppc.
+if [ "x$RC_TARGET_CONFIG" = "xiPhone" ]; then
+  ARM_DARWIN_TARGET_IPHONEOS="YES"
+fi
 
+if [ -n "$ARM_SDK" ]; then
   ARM_PLATFORM=`xcodebuild -version -sdk $ARM_SDK PlatformPath`
   ARM_SYSROOT=`xcodebuild -version -sdk $ARM_SDK Path`
-  ARM_TOOLROOT=$ARM_PLATFORM/Developer
-
-elif [ "x$RC_TARGET_CONFIG" = "xiPhone" ]; then
-
-  # If the build target is iPhone, use the iPhone SDK as the build sysroot
-  # and use the tools from the iPhone platform directory.  FIXME: This is a
-  # temporary fallback for builds where ARM_SDK is not set.  It can be removed,
-  # along with the following bootstrap SDK fallback, when ARM_SDK is set for
-  # all builds.
-  ARM_PLATFORM=/Developer/Platforms/iPhoneOS.platform
-  ARM_IPHONE_SDK=iPhoneOS${IPHONEOS_DEPLOYMENT_TARGET}.Internal.sdk
-
-  ARM_SYSROOT=$ARM_PLATFORM/Developer/SDKs/$ARM_IPHONE_SDK
-  ARM_TOOLROOT=$ARM_PLATFORM/Developer
-
 else
-
   # Use bootstrap SDK if it is available.
+  # FIXME: This can be removed once all builds set ARM_SDK.
   if [ -d /Developer/SDKs/Extra ]; then
     ARM_SYSROOT=/Developer/SDKs/Extra
   else
     ARM_SYSROOT=/
   fi
   ARM_PLATFORM=/
-  ARM_TOOLROOT=/
-
 fi
 ARM_CONFIGFLAGS="$ARM_CONFIGFLAGS --with-build-sysroot=\"$ARM_SYSROOT\""
 
@@ -169,10 +163,6 @@ fi
 if echo $TARGETS | grep arm; then
   if [ ! -d $ARM_SYSROOT ]; then
     echo "Error: cannot find ARM SDK to build ARM target"
-    exit 1
-  fi
-  if [ ! -d $ARM_TOOLROOT ]; then
-    echo "Error: $ARM_TOOLROOT directory is not installed"
     exit 1
   fi
   if [ "x$ARM_MULTILIB_ARCHS" = "x" ] ; then
@@ -266,20 +256,22 @@ if [ "$ENABLE_LLVM" == true ]; then
   MAKEFLAGS="$MAKEFLAGS BUILD_LLVM_APPLE_STYLE=1"
   # Build llvm-gcc in 'dylib mode'.
   MAKEFLAGS="$MAKEFLAGS BUILD_LLVM_INTO_A_DYLIB=1"
-  MAKEFLAGS="$MAKEFLAGS LLVM_VERSION_INFO=$LLVM_SUBMIT_VERSION"
+  if [ x$LLVM_SUBMIT_SUBVERSION == x ]; then
+      MAKEFLAGS="$MAKEFLAGS LLVM_VERSION_INFO=$LLVM_SUBMIT_VERSION"
+  else
+      MAKEFLAGS="$MAKEFLAGS LLVM_VERSION_INFO=$LLVM_SUBMIT_VERSION.$LLVM_SUBMIT_SUBVERSION"
+  fi
 fi
 # LLVM LOCAL end
 
 # If the user has set CC or CXX, respect their wishes.  If not,
-# compile with LLVM-GCC/LLVM-G++ if available; if LLVM is not
+# compile with clang/clang++ if available; if LLVM is not
 # available, fall back to usual GCC/G++ default.
-savedPATH=$PATH ; PATH="/Developer/usr/bin:$PATH"
-XTMPCC=$(which llvm-gcc)
+XTMPCC=`xcrun -find clang`
 if [ x$CC  = x -a x$XTMPCC != x ] ; then export CC=$XTMPCC  forcedCC=1  ; fi
-XTMPCC=$(which llvm-g++)
+XTMPCC=`xcrun -find clang++`
 if [ x$CXX = x -a x$XTMPCC != x ] ; then export CXX=$XTMPCC forcedCXX=1 ; fi
-PATH=$savedPATH
-unset XTMPCC savedPATH
+unset XTMPCC
 
 # Build the native GCC.  Do this even if the user didn't ask for it
 # because it'll be needed for the bootstrap.
@@ -320,36 +312,37 @@ PATH=$DIR/dst-$BUILD-$BUILD$DEST_ROOT/bin:$PATH
 rm -rf $DIR/bin || exit 1
 mkdir $DIR/bin || exit 1
 for prog in ar nm ranlib strip lipo ld ; do
-  for t in `echo $TARGETS $HOSTS | sort -u`; do
+  for t in `echo $TARGETS $HOSTS | tr ' ' '\n' | sort -u`; do
     P=$DIR/bin/${t}-apple-darwin$DARWIN_VERS-${prog}
-    # APPLE LOCAL begin toolroot
-    if [ $t = "arm" ]; then
-      toolroot=$ARM_TOOLROOT
+    # Use the specified ARM_SDK for arm, but otherwise force the SDK to / for
+    # now, since SDKROOT may be set to an SDK that does not include support
+    # for all the targets being built (i.e., ppc).
+    if [ "$t" = "arm" -a -n "$ARM_SDK" ]; then
+      sdkoption="-sdk $ARM_SDK"
     else
-      toolroot=
+      sdkoption="-sdk /"
     fi
-    # APPLE LOCAL end toolroot
+    progpath=`xcrun $sdkoption -find $prog`
     echo '#!/bin/sh' > $P || exit 1
-    # APPLE LOCAL insert toolroot below
-    echo 'exec '${toolroot}'/usr/bin/'${prog}' "$@"' >> $P || exit 1
+    echo 'exec '${progpath}' "$@"' >> $P || exit 1
     chmod a+x $P || exit 1
   done
 done
-for t in `echo $1 $2 | sort -u`; do
+# The "as" script adds a default "-arch" option.  Iterate over the lists of
+# untranslated HOSTS and TARGETS in $1 and $2 so those names can be used as
+# the arguments for "-arch" in the scripts.
+for t in `echo $1 $2 | tr ' ' '\n' | sort -u`; do
   gt=`echo $t | $TRANSLATE_ARCH`
   P=$DIR/bin/${gt}-apple-darwin$DARWIN_VERS-as
-  # APPLE LOCAL begin toolroot
-  if [ $gt = "arm" ]; then
-    toolroot=$ARM_TOOLROOT
+  if [ "$gt" = "arm" -a -n "$ARM_SDK" ]; then
+    sdkoption="-sdk $ARM_SDK"
   else
-    toolroot=
+    sdkoption="-sdk /"
   fi
-  # APPLE LOCAL end toolroot
+  progpath=`xcrun $sdkoption -find as`
   echo '#!/bin/sh' > $P || exit 1
-
-  # APPLE LOCAL insert toolroot below
-  echo 'for a; do case $a in -arch) exec '${toolroot}'/usr/bin/as "$@";;  esac; done' >> $P || exit 1
-  echo 'exec '${toolroot}'/usr/bin/as -arch '${t}' "$@"' >> $P || exit 1
+  echo 'for a; do case $a in -arch) exec '${progpath}' "$@";;  esac; done' >> $P || exit 1
+  echo 'exec '${progpath}' -arch '${t}' "$@"' >> $P || exit 1
   chmod a+x $P || exit 1
 done
 PATH=$DIR/bin:$PATH
@@ -380,14 +373,27 @@ for t in $CROSS_TARGETS ; do
       AS_FOR_TARGET=$DIR/bin/${t}-apple-darwin$DARWIN_VERS-as \
       LD_FOR_TARGET=$DIR/bin/${t}-apple-darwin$DARWIN_VERS-ld \
       $SRC_DIR/configure $T_CONFIGFLAGS $ARM_CONFIGFLAGS || exit 1
+    elif [ $t = 'powerpc' ] ; then
+      $SRC_DIR/configure $T_CONFIGFLAGS $PPC_CONFIGFLAGS || exit 1
     else
       $SRC_DIR/configure $T_CONFIGFLAGS $NON_ARM_CONFIGFLAGS || exit 1
     fi
     # APPLE LOCAL end ARM ARM_CONFIGFLAGS
    fi
-   make $MAKEFLAGS all CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
+   if [ $t = 'arm' ] ; then
+     if [ $ARM_DARWIN_TARGET_IPHONEOS = 'YES' ] ; then
+       DEFAULT_TARGET="-DDEFAULT_TARGET_OS=DARWIN_VERSION_IPHONEOS"
+     else
+        DEFAULT_TARGET="-DDEFAULT_TARGET_OS=DARWIN_VERSION_MACOSX"
+     fi
+   else
+     DEFAULT_TARGET=""
+   fi
+   make $MAKEFLAGS all CFLAGS="$CFLAGS $DEFAULT_TARGET" \
+     CXXFLAGS="$CFLAGS $DEFAULT_TARGET" || exit 1
    make $MAKEFLAGS DESTDIR=$DIR/dst-$BUILD-$t install-gcc install-target \
-     CFLAGS="$CFLAGS" CXXFLAGS="$CFLAGS" || exit 1
+     CFLAGS="$CFLAGS $DEFAULT_TARGET" \
+     CXXFLAGS="$CFLAGS $DEFAULT_TARGET" || exit 1
 
    # Add the compiler we just built to the path.
    # LLVM LOCAL Support for non /usr $DEST_ROOT
@@ -430,6 +436,8 @@ for h in $HOSTS ; do
           --target=$t-apple-darwin$DARWIN_VERS"
 	if [ $t = 'arm' ] && [ $h != 'arm' ] ; then
           T_CONFIGFLAGS="$T_CONFIGFLAGS $ARM_CONFIGFLAGS"
+	elif [ $t = 'powerpc' ] && [ $h != 'powerpc' ] ; then
+          T_CONFIGFLAGS="$T_CONFIGFLAGS $PPC_CONFIGFLAGS"
         else
           T_CONFIGFLAGS="$T_CONFIGFLAGS $NON_ARM_CONFIGFLAGS"
         fi
@@ -437,11 +445,18 @@ for h in $HOSTS ; do
 	# APPLE LOCAL end ARM ARM_CONFIGFLAGS
       fi
 
-      # For ARM, we need to make sure it picks up the ARM_TOOLROOT versions
+      # For ARM, we need to make sure it picks up the correct versions
       # of the linker and cctools.
       if [ $t = 'arm' ] ; then
+        if [ -n "$ARM_SDK" ]; then
+          sdkoption="-sdk $ARM_SDK"
+        else
+          sdkoption="-sdk /"
+        fi
+        progpath=`xcrun $sdkoption -find ld`
+        comppath=`dirname $progpath`
         ORIG_COMPILER_PATH=$COMPILER_PATH
-        export COMPILER_PATH=$ARM_TOOLROOT/usr/bin:$COMPILER_PATH
+        export COMPILER_PATH=$comppath:$COMPILER_PATH
       fi
 
       if [ $h = $t ] ; then
@@ -510,6 +525,7 @@ for t in $TARGETS ; do
   # LLVM LOCAL begin fix broken link
   ln -s ../../../../../bin/as .$DL/as
   ln -s ../../../../../bin/ld .$DL/ld
+  ln -s ../../../../../bin/dsymutil .$DL/dsymutil
   # LLVM LOCAL end fix broken link
 done
 
@@ -573,21 +589,8 @@ for t in $LIBGOMP_TARGETS ; do
 done
 # APPLE LOCAL end native compiler support
 
-if [ $BUILD_CXX -eq 1 ]; then
-for t in $TARGETS ; do
-    if [ "$t" == 'arm' ] ; then
-        cp -p $ARM_SYSROOT/usr/lib/libstdc++.6.dylib \
-            .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib \
-            || exit 1
-    else
-        cp -p /usr/lib/libstdc++.6.dylib \
-            .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib \
-            || exit 1
-    fi
-# LLVM LOCAL
-#  strip -x -c .$DEST_ROOT/lib/gcc/$t-apple-darwin$DARWIN_VERS/$VERS/libstdc++.dylib || exit 1
-done
-fi
+# LLVM LOCAL remove libstdc++ copying
+
 
 # include
 HEADERPATH=$DEST_ROOT/include/gcc/darwin/$MAJ_VERS
@@ -631,19 +634,20 @@ for t in $TARGETS ; do
 done
 
 # LLVM LOCAL begin
-# Compress manpages
-gzip -f $MDIR/*
-
 if [ "x$RC_ProjectName" = "xllvmgcc42_Embedded" ]; then
 MAN1_DIR=${DEST_DIR}${ARM_PLATFORM}/Developer/usr/share/man/man1
 else
-MAN1_DIR=$DEST_DIR/Developer/usr/share/man/man1
+MAN1_DIR=$DEST_DIR$DEST_ROOT/../share/man/man1
 fi
 mkdir -p ${MAN1_DIR}
+for i in gcc.1 g++.1 cpp.1 gcov.1 ; do
+    cp $DIR/obj-$BUILD-$BUILD/gcc/doc/$i ${MAN1_DIR}/$i
+done
 cp $ORIG_SRC_DIR/gcc/doc/llvm-gcc.1 ${MAN1_DIR}/llvm-gcc.1
+# llvm-g++ manpage is a dup of llvm-gcc manpage
 cp $ORIG_SRC_DIR/gcc/doc/llvm-gcc.1 ${MAN1_DIR}/llvm-g++.1
-gzip -f ${MAN1_DIR}/llvm-gcc.1
-gzip -f ${MAN1_DIR}/llvm-g++.1
+# Compress manpages
+gzip -f $MDIR/* ${MAN1_DIR}/*
 # LLVM LOCAL end
 
 # Build driver-driver using fully-named drivers
@@ -758,26 +762,34 @@ for t in $TARGETS ; do
     ln -s ../../libllvmgcc.dylib
 done
 
-if [ "x$RC_ProjectName" == "xllvmgcc42_Embedded" ]; then
-    if [ "x$LLVM_BUILT_ROOTS" == "x" ]; then
-        mkdir -p $DEST_DIR${ARM_PLATFORM}/usr/bin
-        cd $DEST_DIR${ARM_PLATFORM}/usr/bin
-        ln -s ${ARM_PLATFORM}/Developer/usr/bin/llvm-gcc-4.2 llvm-gcc-4.2
-        ln -s ${ARM_PLATFORM}/Developer/usr/bin/llvm-g++-4.2 llvm-g++-4.2
-    fi
-else
-    if [ "x$LLVM_BUILT_ROOTS" == "x" ]; then
-        mkdir -p $DEST_DIR/usr/bin
-        cd $DEST_DIR/usr/bin
-        ln -s /Developer/usr/bin/llvm-gcc-4.2 llvm-gcc-4.2
-        ln -s /Developer/usr/bin/llvm-g++-4.2 llvm-g++-4.2
-    fi
-fi
-
 # Remove unwind.h from the install directory for > 10.6
 if [ $DARWIN_VERS -gt 10 ]; then
     find $DEST_DIR -name "unwind.h" -print | xargs rm || exit 1
 fi
+
+# Install libLTO.dylib
+if [ "$INSTALL_LIBLTO" == yes ]; then
+  LTO=$LLVMCORE_PATH/lib/libLTO.dylib
+  if [ ! -r $LTO  ]; then
+    LTO=$LLVMCORE_PATH/../lib/libLTO.dylib
+    if [ ! -r $LTO ]; then
+      echo "Error: llvmCore installation is missing libLTO.dylib"
+      exit 1
+    fi
+  fi
+  mkdir -p $DEST_DIR/Developer/usr/lib
+  cp $LTO $DEST_DIR/Developer/usr/lib/libLTO.dylib
+  strip -S $DEST_DIR/Developer/usr/lib/libLTO.dylib
+
+  # Add a symlink in /usr/lib for B&I.
+  mkdir -p $DEST_DIR/usr/lib/
+  cd $DEST_DIR/usr/lib && \
+    ln -s ../../Developer/usr/lib/libLTO.dylib ./libLTO.dylib
+fi
+
+# Remove lto.h from the install directory; clang will supply.
+# Also remove ppc_intrinsics.h.  Note that this breaks PPC support.
+find $DEST_DIR \( -name lto.h -o -name ppc_intrinsics.h \) -delete -print || exit 1
 
 # LLVM LOCAL end
 
